### ISSUE TITLE
Parsing error AtoI - Usecase: Apply default option to all images

### ISSUE THREAD

**Issue by amenk** [ultimate-guitar/reImage#3]
I have an OpenStreetMap tile server and try to run pngquant on it via reImage, but I am getting:

     reImage       | 2019/03/16 15:40:53 Can not parse
         requested url: 'http://reimage:7075/7/77/60.png?t=1552744964197',
         err: reWidth value '/7/77/60.png' parsing
         error: strconv.Atoi: parsing "/7/77/60.png": invalid syntax

Request URL to reimage:

    http://localhost:8080/7/77/60.png

Proxy Settings:

             proxy_set_header X-RESIZE-SCHEME "http";
             proxy_set_header X-RESIZE-BASE "localhost:6789/openstreetmap-carto/tile/";

**Comment by larrabee** [comment]
Hello. 
You have invalid configuration.
For your case you should use this settings:  
Proxy settings:  
```
proxy_set_header X-RESIZE-SCHEME "http";
proxy_set_header X-RESIZE-BASE "localhost:6789";
```
And you should request images like this:
[http://reimage:7075/7/77/60.png@1280?t=1552744964197](http://reimage:7075/7/77/60.png@1280?t=1552744964197) (for 1280xYYY)  
or  
(http://reimage:7075/7/77/60.png@x720?t=1552744964197) (for YYYx720)

**Comment by amenk** [comment]
But I need a subfolder ...

it looks like I have some other misunderstanding: reImage always wants to know to which size to resize to, while my usecase is more to proxy all images and just apply pngquant.

I think I need something like this to specify the default options for .png files in the nginx configuration:

             rewrite (.*\.png) $1@?cmp=9 break;

**Comment by larrabee** [comment]
Sorry, i have the mistake.
URL should like this:
[http://reimage:7075/openstreetmap-carto/tile/7/77/60.png@10000?t=1552744964197](http://reimage:7075/openstreetmap-carto/tile/7/77/60.png@10000?t=1552744964197)  

For your case you can set big resolution, like @10000. Images will not resized (if it smaller than 10k) but pngquant will applied.  
So your config something like this:
```
rewrite (.*\.png) $1@10000?cmp=9 break;
```

**Comment by amenk** [comment]
actually

rewrite (.*\.png) $1@?cmp=9 break;

also seems to work well.

And the reasons I am putting 

         proxy_set_header X-RESIZE-BASE "localhost:6789/openstreetmap-carto/tile/";

is that I want to remove openstreetmap-carto/tile from the path --> that is working well.

rewrite works very fine now, thanks for sharing that great work :-)
