### ISSUE TITLE
Is there any example of how to upload images to the server ?

### ISSUE THREAD

**Issue by SergeyStorm** [ultimate-guitar/reImage#5]
Hello!
I'm trying to use your software but I can't figure out how to upload images to the server.
I started a container and set a frontend up.
Now I'm trying to upload image with curl, but without success:
```curl -vv -F 'data=@./bird_1920x1279.jpg' http://localhost/img/test.jpg``` (different variations of this)

log in container says the following:

```
2019/08/17 10:20:18 Can not parse requested url: 'http://127.0.0.1:7075/test.jpg', err: reWidth value '/test.jpg' parsing error: strconv.Atoi: parsing "/test.jpg": invalid syntax
2019/08/17 10:23:24 Can not parse requested url: 'http://127.0.0.1:7075/test.jpg', err: reWidth value '/test.jpg' parsing error: strconv.Atoi: parsing "/test.jpg": invalid syntax
2019/08/17 10:26:04 Can not parse requested url: 'http://127.0.0.1:7075/bird_1920x1279.jpg', err: reWidth value '/bird_1920' parsing error: strconv.Atoi: parsing "/bird_1920": invalid syntax
```
Could you, please, describe how to done with this ?

**Comment by larrabee** [comment]
Hello. Are you setup nginx as frontend server, right?  
You should upload images to your frontend server. For nginx just copy image file into document root (in example document root is `root /var/www/example.com/`.)  
So copy image to this directory like this `cp image.jpg /var/www/example.com/` and try to get from browser [http://localhost/image.jpg](http://localhost/image.jpg).
After it's you can try to get resizer version [http://localhost/image.jpg@100](http://localhost/image.jpg@100).

**Comment by SergeyStorm** [comment]
Thank you for  the help.
Yes, I set up nginx as a frontend.
I uploaded an image to the server root and triyng to get it in browser. Browser says: 400
Container log says following (I tried two different paths):
```
2019/08/17 11:21:51 Can not parse requested url: 'http://localhost:7075/test.jpg', err: empty 'x-resize-base' header on GET request
2019/08/17 11:22:25 Can not parse requested url: 'http://localhost:7075/img/test.jpg', err: empty 'x-
resize-base' header on GET request
```

**Comment by larrabee** [comment]
1. Can you download original image [http://localhost/test.jpg](http://localhost/test.jpg)?
2. You should not do request to reImage directly. You should do request through nginx because nginx will add configuration headers (`X-RESIZE-BASE` and `X-RESIZE-SCHEME`).
3. If you still want to do requests directly ro reImage you should do it like this:
```
curl -H 'X-RESIZE-BASE: localhost' -H 'X-RESIZE-SCHEME: http' 'http://localhost:7075/test.jpg@100'
```

**Comment by SergeyStorm** [comment]
I figured it out.
Thanks for your help again!
It was bad idea to use "localhost" as a domain, because the reimage also uses this address to access the image and thus attempting to download the image from its localhost.
