### ISSUE TITLE
Background option support

### ISSUE THREAD

**Issue by astronom** [ultimate-guitar/reImage#6]
Hi! 
Are you planning to add Background option from https://github.com/h2non/bimg/blob/15cd11560781e3a634d3857b845d4c9c93aa454b/options.go#L215

It will be useful for resize with both set height and width, when original image can not be autoscale without crop or adding backgroud. By default it is black
![djk4ytr2YwN7YNc7kHWoeVrlYbBK jpg@79x82](https://user-images.githubusercontent.com/729063/65258919-33235980-db1d-11e9-93ca-b2eb0bf8b202.jpeg)

**Comment by larrabee** [comment]
Привет.
Нет, я не планировал. Выглядит совсем не сложным в добавлении.

**Comment by astronom** [comment]
Я на go еще ничего не писал, а эта фича была бы для нас полезной

**Comment by larrabee** [comment]
Я добавил эту опцию, пример использования есть в README.

**Comment by larrabee** [comment]
Функция добавлена, но я обнаружил, что она она работает некорректно. Проблема в библиотеке libvips (или в биндинге к ней). Пока нет времени разбираться и править код либы.  
Она работает с JPEG картинками, но падает на PNG.

**Comment by larrabee** [comment]
Реализация добавлена в последнюю версию.
